class Satellite < ApplicationRecord
  has_one :orbit, inverse_of: :satellite

  # validates :tles, length: { maximum: 162 }
  # validates :tles, format: { with: /^[A-Z0-9\+\- ]*$/, message: 'can only contain capital letters, numbers, spaces, and pluses and minus signs' }

  # scope :rocket_bodies, -> { where(space_object_type: 'ROCKET BODY') }
  # scope :payloads, -> { where(space_object_type: 'PAYLOAD') }
  # scope :debris, -> { where(space_object_type: 'DEBRIS')
  # scope :unknown, -> { where(space_object_type: 'TBA') }

  # scope :in_orbit, -> { where(decay_date: nil) }
  # scope :decayed, -> { where.not(decay_date: nil) }

  # scope :starlink, -> { where('name ILIKE ?', 'STARLINK%') }

  def self.list_of_countries
    [
      'Arab Satellite Communications Organization',
      'Asiasat Corp',
      'Republic of Angola',
      'Algeria',
      'Argentina',
      'Austria',
      'Australia',
      'Azerbaijan',
      'Belgium',
      'Belarus',
      'Bermuda',
      'Bangladesh',
      'Bulgaria',
      'Bolivia',
      'Brazil',
      'Canada',
      'China/Brazil',
      'Chile',
      'USSR/Russia',
      'Colombia',
      'Costa Rica',
      'Czechoslovakia',
      'Denmark',
      'Ecuador',
      'Egypt',
      'European Space Agency (ESA)',
      'European Space Research Organization (ESRO)',
      'Estonia',
      'European Organization For The Exploitation Of Meteorological Satellites',
      'European Telecommunications Satellite Organization (EUTELSAT)',
      'France/Germany',
      'Finland',
      'France',
      'France/Italy',
      'Germany',
      'Ghana',
      'Globalstar',
      'Greece',
      'Hungary',
      'International Maritime Satellite Organization (INMARSAT)',
      'India',
      'Indonesia',
      'Iran',
      'Iraq',
      'Israel',
      'International Space Station (ISS)',
      'Italy',
      'International Telecommunications Satellite Organization (INTELSAT)',
      'Jordan',
      'Japan',
      'Kazakhstan',
      'Kenya',
      'Laos',
      'Sri Lanka',
      'Lithuania',
      'Luxembourg',
      'Morocco',
      'Malaysia',
      'Mexico',
      'Mongolia',
      'North Atlantic Treaty Organization (NATO)',
      'Netherlands',
      'New ICO',
      'Nigeria',
      'North Korea',
      'Norway',
      'Nepal',
      'New Zealand',
      'O3B Networks',
      'Orbital Telecommunications Satellite (Globalstar)',
      'Pakistan',
      'Peru',
      'Poland',
      'Portugal',
      'China',
      'Regional African Satellite Communications Org',
      'Taiwan',
      'Romania',
      'Philippines',
      'Rwanda',
      'South Africa',
      'Saudi Arabia',
      'Sudan',
      'Sea Launch Demo',
      'Société Européenne Des Satellites (SES)',
      'Singapore',
      'South Korea',
      'Spain',
      'Singapore/Taiwan',
      'Sweden',
      'Switzerland',
      'To Be Determined/Unknown',
      'Thailand',
      'Turkmenistan/Monaco',
      'Turkey',
      'United Arab Emirates',
      'United Kingdom',
      'Ukraine',
      'Uruguay',
      'United States Of America',
      'United States/Brazil',
      'Venezuela',
      'Vietnam'
    ]
  end

  def self.country_conversions
    {
      'AB': 'Arab Satellite Communications Organization',
      'AC': 'Asiasat Corp',
      'AGO': 'Republic of Angola',
      'ALG': 'Algeria',
      'ARGN': 'Argentina',
      'ASRA': 'Austria',
      'AUS': 'Australia',
      'AZER': 'Azerbaijan',
      'BEL': 'Belgium',
      'BELA': 'Belarus',
      'BERM': 'Bermuda',
      'BGD': 'Bangladesh',
      'BGR': 'Bulgaria',
      'BOL': 'Bolivia',
      'BRAZ': 'Brazil',
      'CA': 'Canada',
      'CHBZ': 'China/Brazil',
      'CHLE': 'Chile',
      'CIS': 'USSR/Russia',
      'COL': 'Colombia',
      'CRI': 'Costa Rica',
      'CZCH': 'Czechoslovakia',
      'DEN': 'Denmark',
      'ECU': 'Ecuador',
      'EGYP': 'Egypt',
      'ESA': 'European Space Agency (ESA)',
      'ESRO': 'European Space Research Organization (ESRO)',
      'EST': 'Estonia',
      'EUME': 'European Organization For The Exploitation Of Meteorological Satellites',
      'EUTE': 'European Telecommunications Satellite Organization (EUTELSAT)',
      'FGER': 'France/Germany',
      'FIN': 'Finland',
      'FR': 'France',
      'FRIT': 'France/Italy',
      'GER': 'Germany',
      'GHA': 'Ghana',
      'GLOB': 'Globalstar',
      'GREC': 'Greece',
      'HUN': 'Hungary',
      'IM': 'International Maritime Satellite Organization (INMARSAT)',
      'IND': 'India',
      'INDO': 'Indonesia',
      'IRAN': 'Iran',
      'IRAQ': 'Iraq',
      'ISRA': 'Israel',
      'ISS': 'International Space Station (ISS)',
      'IT': 'Italy',
      'ITSO': 'International Telecommunications Satellite Organization (INTELSAT)',
      'JOR': 'Jordan',
      'JPN': 'Japan',
      'KAZ': 'Kazakhstan',
      'KEN': 'Kenya',
      'LAOS': 'Laos',
      'LKA': 'Sri Lanka',
      'LTU': 'Lithuania',
      'LUXE': 'Luxembourg',
      'MA': 'Morocco',
      'MALA': 'Malaysia',
      'MEX': 'Mexico',
      'MNG': 'Mongolia',
      'NATO': 'North Atlantic Treaty Organization (NATO)',
      'NETH': 'Netherlands',
      'NICO': 'New ICO',
      'NIG': 'Nigeria',
      'NKOR': 'North Korea',
      'NOR': 'Norway',
      'NPL': 'Nepal',
      'NZ': 'New Zealand',
      'O3B': 'O3B Networks',
      'ORB': 'Orbital Telecommunications Satellite (Globalstar)',
      'PAKI': 'Pakistan',
      'PER': 'Peru',
      'POL': 'Poland',
      'POR': 'Portugal',
      'PRC': 'China',
      'RASC': 'Regional African Satellite Communications Org',
      'ROC': 'Taiwan',
      'ROM': 'Romania',
      'RP': 'Philippines',
      'RWA': 'Rwanda',
      'SAFR': 'South Africa',
      'SAUD': 'Saudi Arabia',
      'SDN': 'Sudan',
      'SEAL': 'Sea Launch Demo',
      'SES': 'Société Européenne Des Satellites (SES)',
      'SING': 'Singapore',
      'SKOR': 'South Korea',
      'SPN': 'Spain',
      'STCT': 'Singapore/Taiwan',
      'SWED': 'Sweden',
      'SWTZ': 'Switzerland',
      'TBD': 'To Be Determined/Unknown',
      'THAI': 'Thailand',
      'TMMC': 'Turkmenistan/Monaco',
      'TURK': 'Turkey',
      'UAE': 'United Arab Emirates',
      'UK': 'United Kingdom',
      'UKR': 'Ukraine',
      'URY': 'Uruguay',
      'US': 'United States Of America',
      'USBZ': 'United States/Brazil',
      'VENZ': 'Venezuela',
      'VTNM': 'Vietnam'
    }
  end

  def self.list_of_launch_sites
    [
      'Air Force Eastern Test Range',
      'Air Force Western Test Range',
      'Pegasus launched from Canary Islands Air Space',
      'Pegasus launched from Eastern Range Air Space',
      'French Guiana',
      'Hamma Guira Space Track Range, Algeria',
      'Jiuquan Satellite Launch Center, China',
      'Kodiak Island, Alaska, USA',
      'Kagishima Space Center University of Tokyo, Japan',
      'Kwajalein, Marshall Islands',
      'Kapustin Yar Missile and Space Complex, Russia',
      'Naro Space Center, South Korea',
      'Orenburg, Russia',
      'Plesetsk Missile and Space Complex, Russia',
      'Pacific Missile Range Facility, USA',
      'Rocket Lab Launch Complex, New Zealand',
      'Submarine Launch from Barents Sea, Russia',
      'Sea Launch',
      'Semnan, Iran',
      'San Marco Launch Platform, Kenya',
      'Sirharikota, India',
      'Svobodny, Russia',
      'Tanegashima Space Center, Japan',
      'Taiyaun Space Center, China',
      'Tyuratam Missle and Space Complex, Russia',
      'Unknown',
      'Vostochny Cosmodrone, Russia',
      'Wallops Island, Virginia, USA',
      'Woomera, Australia',
      'Pegasus launched from Western Range Air Space',
      'Wenchang Satellite Launch Center, China',
      'Xichang Space Center, China',
      'Yavne, Israel',
      'Yellow Sea Launch Area, China',
      'Yunsong, North Korea'
    ]
  end

  def self.launch_site_conversions
    {
      'AFETR': 'Air Force Eastern Test Range',
      'AFWTR': 'Air Force Western Test Range',
      'CAS': 'Pegasus launched from Canary Islands Air Space',
      'ERAS': 'Pegasus launched from Eastern Range Air Space',
      'FRGUI': 'French Guiana',
      'HGSTR': 'Hamma Guira Space Track Range, Algeria',
      'JSC': 'Jiuquan Satellite Launch Center, China',
      'KODAK': 'Kodiak Island, Alaska, USA',
      'KSCUT': 'Kagishima Space Center University of Tokyo, Japan',
      'KWAJL': 'Kwajalein, Marshall Islands',
      'KYMTR': 'Kapustin Yar Missile and Space Complex, Russia',
      'NSC': 'Naro Space Center, South Korea',
      'OREN': 'Orenburg, Russia',
      'PKMTR': 'Plesetsk Missile and Space Complex, Russia',
      'PMRF': 'Pacific Missile Range Facility, USA',
      'RLLC': 'Rocket Lab Launch Complex, New Zealand',
      'SADOL': 'Submarine Launch from Barents Sea, Russia',
      'SEAL': 'Sea Launch',
      'SEM': 'Semnan, Iran',
      'SNMLP': 'San Marco Launch Platform, Kenya',
      'SRI': 'Sirharikota, India',
      'SVOB': 'Svobodny, Russia',
      'TNSTA': 'Tanegashima Space Center, Japan',
      'TSC': 'Taiyaun Space Center, China',
      'TTMTR': 'Tyuratam Missle and Space Complex, Russia',
      'UNKN': 'Unknown',
      'VOSTO': 'Vostochny Cosmodrone, Russia',
      'WLPIS': 'Wallops Island, Virginia, USA',
      'WOMRA': 'Woomera, Australia',
      'WRAS': 'Pegasus launched from Western Range Air Space',
      'WSC': 'Wenchang Satellite Launch Center, China',
      'XSC': 'Xichang Space Center, China',
      'YAVNE': 'Yavne, Israel',
      'YSLA': 'Yellow Sea Launch Area, China',
      'YUN': 'Yunsong, North Korea'
    }
  end

  def self.list_of_space_object_types
    [
      'Payload',
      'Rocket Body',
      'Debris',
      'Unknown'
    ]
  end

  def self.list_of_radar_cross_section_sizes
    [
      'Small',
      'Medium',
      'Large',
      'Unknown'
    ]
  end
end
